server:
  servlet:
    session:
      timeout: 30
    context-path: /DevMock
  port: 9100
spring:
  thymeleaf:
    prefix: classpath:/static/HTML/
    suffix: .html
    enabled: true
  liquibase:
    enabled: false

logging:
  level:
    com:
      jb4dc:
        base:
          dbaccess:
            dao: TRACE
